### ISSUE TITLE
Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value ()

### ISSUE THREAD

**Issue by seth35us** [Wayaer/fl_camera#1]
I am getting a null reference exception in the code below on iOS. It happens when I put the camera into a bottom navigation bar and then quickly change tabs as soon as the application is launched. The crash is easily repeatable. I have attached a modified lib from the fl_mlkit_scanning example to duplicate the error. 

#1	0x0000000103e449e4 in specialized FlCamera.observeValue(forKeyPath:of:change:context:) ()

  ```
  override public func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey: Any]?, context: UnsafeMutableRawPointer?) {
    if keyPath == #keyPath(AVCaptureDevice.torchMode) {
        // off = 0; on = 1; auto = 2;
        let state = change?[.newKey] as? Int
        var flash: Bool?
        if state != 2 {
            flash = state == 1
        }
        _flCameraEvent.sendEvent(["flash": flash])
    } else if keyPath == #keyPath(AVCaptureDevice.videoZoomFactor) {
        let zoom = change?[.newKey] as? Double
        _flCameraEvent.sendEvent(["zoomRatio": zoom ?? 1, "maxZoomRatio": _device!.activeFormat.videoMaxZoomFactor])
    }
}
```
[lib.zip](https://github.com/Wayaer/fl_camera/files/7230059/lib.zip)

Thanks again for the package, it is really good other than the crash.

**Comment by Wayaer** [comment]
The bug has been fixed. Please update the plug-in to the latest version

**Comment by seth35us** [comment]
The fix works great. Any ideas on how to stop the phone from heating up while using the scanner? I was thinking about reducing camera resolution.

**Comment by Wayaer** [comment]
This is the only way at present

**Comment by seth35us** [comment]
Okay, thanks for looking into it. I still think this is the best package.
