### ISSUE TITLE
Crash: copyPixelBuffer in FlCamera.swift

### ISSUE THREAD

**Issue by seth35us** [Wayaer/fl_camera#4]
There was crash on an iPhone 5s in the copyPixelBuffer method. The crash information is below. 

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000f796148d0

s9fl_camera8FlCameraC15copyPixelBuffers9UnmanagedVySo11CVBufferRefaGSgyFTo

**Comment by Wayaer** [comment]
The question left me without a clue.😅
