### ISSUE TITLE
ios上遇到不调用相机问题

### ISSUE THREAD

**Issue by peakandyuri** [Wayaer/fl_camera#5]
plist文件中声明了相机权限，但是privacy中没有相机权限，搜索了一圈说的是要使用过相机才会有，但是这个插件运行了也似乎没有去请求相机，就导致一直没相权限，代码中使用Permission.camera.request()去请求相机权限也不行。

**Comment by peakandyuri** [comment]
要全新的app才行，如果app之前使用过相机，就不能复现这个问题

**Comment by peakandyuri** [comment]
就是使用permission_handler这个插件去获取相机权限了，安卓上没有问题，但是ios就没有反应，不会弹出授权的actionsheet。因为我是早期用的其它扫码插件，在ios上都正常提示授权了，而换成了fl_mlkit_scanner之后，ios新机就不会提示授权，而之前安装过app并且授过权的机器，使用fl_mlkit_scanner插件相机就是正常的，所以我觉得这个插件应该要主动去获取授权。而我必须要马上解决这个问题，现在我只能再装一个其它相机插件，用它获取授权之后再切换成fl_mlkit_scanner，所以就特别麻烦。

**Comment by Wayaer** [comment]
![image](https://user-images.githubusercontent.com/17231965/217128690-82950aed-3bed-44b8-9014-dc567bcd69c3.png)
如果你使用了最新的permission_handler 需要在ios/profile中配置这些内容，具体参考[permission_handler](https://pub.dev/packages/permission_handler) 的配置

**Comment by peakandyuri** [comment]
在podfile中单独加上这段配置后，卸载原app重新debug安装好像是能能弹出授权提示了，等我再找一个新机器确认一下如果都能弹出就没问题了
